#!/usr/bin/env python3
"""Pack the dcc-mcp UXP plugin into a .ccx archive.

A .ccx file is a renamed ZIP archive containing the plugin files.
It can be installed via:
  - Creative Cloud Desktop App > Plugins > Manage Plugins > Install from file...
  - Photoshop > Plugins > Development > Load Plugin (during development)

Usage::

    python tools/pack_plugin.py                          # output to dist/plugin/
    python tools/pack_plugin.py --output /some/path      # custom output dir
    python tools/pack_plugin.py --version 0.2.0          # set version in manifest
    python tools/pack_plugin.py --help

The output file name follows the pattern::

    dcc-mcp-photoshop-bridge-<version>.ccx
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import zipfile
from pathlib import Path

# Files / directories to EXCLUDE from the .ccx archive
EXCLUDE_PATTERNS = [
    ".DS_Store",
    "__pycache__",
    "*.pyc",
    "node_modules",
    ".git",
    ".gitignore",
    "*.md",       # README files are not needed at runtime
    "tests",
]

# Project root is two levels up from this script
_SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = _SCRIPT_DIR.parent
PLUGIN_DIR = PROJECT_ROOT / "bridge" / "uxp-plugin"


def _hidden_vbs_launcher(cmd_name: str) -> str:
    """Return a .vbs script that launches a .cmd file without a console window."""
    return (
        f'CreateObject("Wscript.Shell").Run "cmd /c {cmd_name}", 0, False\n'
    )


def _sidecar_launcher(binary_name: str) -> str:
    """Return a .cmd script that starts the sidecar in core host-rpc mode.

    The generated script starts dcc-mcp-server in host-rpc mode where the
    core binary handles both the MCP server and the WebSocket bridge internally.
    No separate Python bridge process is started.
    """
    return (
        "@echo off\r\n"
        "setlocal\r\n"
        'cd /d "%~dp0"\r\n'
        "echo dcc-mcp Photoshop sidecar starting (core host-rpc)...\r\n"
        'if "%DCC_MCP_MCP_PORT%"=="" set "DCC_MCP_MCP_PORT=8765"\r\n'
        'if "%DCC_MCP_WS_PORT%"=="" set "DCC_MCP_WS_PORT=9001"\r\n'
        'if "%DCC_MCP_GATEWAY_PORT%"=="" set "DCC_MCP_GATEWAY_PORT=9765"\r\n'
        'if "%DCC_MCP_REGISTRY_DIR%"=="" set "DCC_MCP_REGISTRY_DIR=%USERPROFILE%\\.dcc-mcp\\registry"\r\n'
        f'powershell -NoProfile -ExecutionPolicy Bypass -Command "'
        f'Start-Process -FilePath \'%~dp0{binary_name}\' -ArgumentList @('
        f'\'--dcc\',\'photoshop\','
        f'\'--mcp-port\',$env:DCC_MCP_MCP_PORT,'
        f'\'--ws-port\',$env:DCC_MCP_WS_PORT,'
        f'\'--gateway-port\',$env:DCC_MCP_GATEWAY_PORT,'
        f'\'--registry-dir\',$env:DCC_MCP_REGISTRY_DIR,'
        f'\'--skill-paths\',\'%~dp0..\\skills\''
        f') -WindowStyle Hidden"\r\n'
        '>> "%~dp0server.log" 2>&1\r\n'
        "echo core host-rpc started.\r\n"
    )


def _posix_sidecar_launcher(server_name: str, bridge_name: str) -> str:
    """Return a POSIX shell script that starts sidecar processes in the background.

    The generated script starts dcc-mcp-server in host-rpc mode where the
    core binary handles both the MCP server and the WebSocket bridge internally.
    No separate Python bridge process is started.

    Args:
        server_name: Name of the server binary (e.g. ``"dcc-mcp-server"``).
        bridge_name: Name of the bridge binary (reserved for future use).
    """
    return (
        "#!/usr/bin/env bash\n"
        "# Auto-generated by pack_plugin.py\n"
        'SIDECAR_DIR="$(cd "$(dirname "$0")" && pwd)"\n'
        'echo "dcc-mcp Photoshop sidecar starting (core host-rpc)..."\n'
        ': "${DCC_MCP_MCP_PORT:=8765}"\n'
        ': "${DCC_MCP_WS_PORT:=9001}"\n'
        ': "${DCC_MCP_GATEWAY_PORT:=9765}"\n'
        ': "${DCC_MCP_REGISTRY_DIR:=$HOME/.dcc-mcp/registry}"\n'
        f'nohup "$SIDECAR_DIR/{server_name}" --dcc photoshop '
        "--mcp-port \"$DCC_MCP_MCP_PORT\" "
        "--ws-port \"$DCC_MCP_WS_PORT\" "
        "--gateway-port \"$DCC_MCP_GATEWAY_PORT\" "
        "--registry-dir \"$DCC_MCP_REGISTRY_DIR\" "
        '--skill-paths "$SIDECAR_DIR/skills" '
        '>> "$SIDECAR_DIR/server.log" 2>&1 &\n'
        'echo "core host-rpc started (PID $!)"\n'
    )


def _sidecar_stopper(binary_name: str) -> str:
    """Return a .cmd script that stops the sidecar server by killing its process."""
    return (
        "@echo off\r\n"
        f"taskkill /f /im {binary_name}\r\n"
    )


def _should_exclude(path: Path, plugin_root: Path) -> bool:
    """Return True if the path should be excluded from the archive."""
    rel = path.relative_to(plugin_root)
    for part in rel.parts:
        for pattern in EXCLUDE_PATTERNS:
            if pattern.startswith("*"):
                if part.endswith(pattern[1:]):
                    return True
            elif part == pattern:
                return True
    return False


# ── Required files for a valid UXP plugin ─────────────────────────────────

_REQUIRED_MANIFEST_FIELDS = [
    "id",
    "name",
    "version",
    "host",
    "entrypoints",
]

_REQUIRED_PLUGIN_FILES = [
    "index.html",
    "index.js",
    "manifest.json",
]


def lint_plugin(plugin_dir: Path) -> list[str]:
    """Run pre-packaging lint checks on the UXP plugin directory.

    Returns a list of warning/error messages (empty list = no issues found).
    Errors are prefixed with ``ERROR:``, warnings with ``WARNING:``.
    """
    issues: list[str] = []

    if not plugin_dir.is_dir():
        issues.append(f"ERROR: Plugin directory not found: {plugin_dir}")
        return issues

    # Check required files exist
    for filename in _REQUIRED_PLUGIN_FILES:
        if not (plugin_dir / filename).is_file():
            issues.append(f"ERROR: Required file missing: {filename}")

    # Check required manifest fields
    manifest_path = plugin_dir / "manifest.json"
    if manifest_path.is_file():
        try:
            with open(manifest_path, encoding="utf-8") as f:
                manifest = json.load(f)

            for field in _REQUIRED_MANIFEST_FIELDS:
                if field not in manifest:
                    issues.append(f"ERROR: manifest.json missing required field: '{field}'")

            # Validate host section
            host = manifest.get("host", {})
            if isinstance(host, dict):
                if "app" not in host:
                    issues.append("ERROR: manifest.json host section missing 'app' field")
                if host.get("app") != "PS":
                    issues.append(f"WARNING: manifest.json host.app is '{host.get('app')}', expected 'PS'")
                if host.get("minVersion"):
                    min_ver = host["minVersion"]
                    if not re.match(r"^\d+\.\d+\.\d+$", str(min_ver)):
                        issues.append(f"WARNING: manifest.json host.minVersion '{min_ver}' does not look like a version")

            # Validate entrypoints
            entrypoints = manifest.get("entrypoints", [])
            if isinstance(entrypoints, list):
                if len(entrypoints) == 0:
                    issues.append("ERROR: manifest.json entrypoints is empty")
                for i, ep in enumerate(entrypoints):
                    if isinstance(ep, dict) and ep.get("type") != "panel":
                        issues.append(f"WARNING: manifest.json entrypoints[{i}] type is not 'panel'")
            else:
                issues.append("ERROR: manifest.json entrypoints must be an array")

            # Validate requiredPermissions
            perms = manifest.get("requiredPermissions", {})
            if isinstance(perms, dict):
                network = perms.get("network", {})
                if isinstance(network, dict) and network.get("domains") != "all":
                    issues.append("WARNING: manifest.json network.domains should be 'all' for WebSocket access")

            # Check version consistency
            man_version = manifest.get("version", "")
            if not re.match(r"^\d+\.\d+\.\d+", str(man_version)):
                issues.append(f"WARNING: manifest.json version '{man_version}' is not semver")

        except json.JSONDecodeError as exc:
            issues.append(f"ERROR: manifest.json is not valid JSON: {exc}")

    # Check that index.html references index.js
    html_path = plugin_dir / "index.html"
    if html_path.is_file():
        html_content = html_path.read_text(encoding="utf-8")
        if 'src="index.js"' not in html_content:
            issues.append("WARNING: index.html does not have a script tag with src='index.js'")

    # Check sidecar directory
    sidecar_dir = plugin_dir / "sidecar"
    if sidecar_dir.is_dir():
        if not any(sidecar_dir.glob("dcc-mcp-server*")):
            issues.append("WARNING: No dcc-mcp-server binary found in sidecar directory")
    else:
        issues.append("WARNING: sidecar directory not found in plugin directory")

    # Check for unwanted files that should be excluded
    _check_unwanted_files(plugin_dir, issues)

    return issues


def _check_unwanted_files(plugin_dir: Path, issues: list[str]) -> None:
    """Check for files that will be excluded from packaging but may indicate issues."""
    for pattern, hint in [
        ("node_modules", "node_modules found — should be excluded from .ccx"),
        (".git", ".git directory found — should be excluded from .ccx"),
        ("*.md", "Markdown files excluded from .ccx (README not needed at runtime)"),
    ]:
        if pattern.startswith("*"):
            matches = list(plugin_dir.rglob(pattern))
            if matches:
                issues.append(f"INFO: {hint} ({len(matches)} file(s))")
        else:
            target = plugin_dir / pattern
            if target.exists():
                issues.append(f"INFO: {hint}")


def pack_plugin(
    plugin_dir: Path,
    output_dir: Path,
    version: str,
) -> Path:
    """Pack the UXP plugin directory into a .ccx archive.

    Args:
        plugin_dir: Path to the ``bridge/uxp-plugin/`` directory.
        output_dir: Directory where the ``.ccx`` file will be written.
        version: Plugin version string (e.g. ``"0.1.0"``).

    Returns:
        Path to the created ``.ccx`` file.
    """
    if not plugin_dir.is_dir():
        print(f"ERROR: Plugin directory not found: {plugin_dir}", file=sys.stderr)
        sys.exit(1)

    manifest_path = plugin_dir / "manifest.json"
    if not manifest_path.exists():
        print(f"ERROR: manifest.json not found in {plugin_dir}", file=sys.stderr)
        sys.exit(1)

    output_dir.mkdir(parents=True, exist_ok=True)

    output_name = f"dcc-mcp-photoshop-bridge-{version}.ccx"
    output_path = output_dir / output_name

    # Update manifest version in memory
    manifest_data = _update_manifest_version(manifest_path, version)

    file_count = 0
    with zipfile.ZipFile(output_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        # Write manifest.json with updated version
        zf.writestr("manifest.json", json.dumps(manifest_data, indent=2))
        file_count += 1

        # Walk the plugin directory and add all non-excluded files
        for file_path in sorted(plugin_dir.rglob("*")):
            if not file_path.is_file():
                continue
            if file_path.name == "manifest.json":
                continue  # already written above
            if _should_exclude(file_path, plugin_dir):
                continue

            arcname = file_path.relative_to(plugin_dir).as_posix()
            zf.write(file_path, arcname)
            file_count += 1

    size_kb = output_path.stat().st_size / 1024
    print(f"Packed {file_count} files → {output_path}  ({size_kb:.1f} KB)")
    return output_path


def _read_version_from_manifest(plugin_dir: Path) -> str:
    """Read the version from manifest.json as a fallback."""
    try:
        with open(plugin_dir / "manifest.json", encoding="utf-8") as f:
            return json.load(f).get("version", "0.0.0")
    except Exception:
        return "0.0.0"


def _read_version_from_pyproject(project_root: Path) -> str:
    """Read the version from pyproject.toml."""
    pyproject = project_root / "pyproject.toml"
    if not pyproject.exists():
        return "0.0.0"
    content = pyproject.read_text(encoding="utf-8")
    m = re.search(r'^version\s*=\s*"([^"]+)"', content, re.MULTILINE)
    return m.group(1) if m else "0.0.0"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Pack the dcc-mcp UXP plugin into a .ccx archive.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--plugin-dir",
        type=Path,
        default=PLUGIN_DIR,
        help=f"Path to the UXP plugin directory (default: {PLUGIN_DIR})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=PROJECT_ROOT / "dist" / "plugin",
        help="Output directory for the .ccx file (default: dist/plugin/)",
    )
    parser.add_argument(
        "--version",
        default=None,
        help="Plugin version (default: read from pyproject.toml)",
    )
    parser.add_argument(
        "--lint",
        action="store_true",
        help="Run pre-packaging lint checks without creating the archive",
    )
    args = parser.parse_args()

    # Resolve version
    version = args.version
    if not version:
        version = _read_version_from_pyproject(PROJECT_ROOT)
    if not version:
        version = _read_version_from_manifest(args.plugin_dir)

    # Validate version format
    if not re.match(r"^\d+\.\d+\.\d+", version):
        print(
            f"WARNING: Version '{version}' does not look like semver. "
            "UXP manifest requires x.y.z format.",
            file=sys.stderr,
        )

    # --lint mode: check without packaging
    if args.lint:
        issues = lint_plugin(args.plugin_dir)
        if issues:
            print("\nPlugin lint results:")
            for issue in issues:
                prefix = issue.split(":")[0]
                if prefix == "ERROR":
                    print(f"  ✗ {issue}")
                elif prefix == "WARNING":
                    print(f"  ⚠ {issue}")
                else:
                    print(f"  ℹ {issue}")
            error_count = sum(1 for i in issues if i.startswith("ERROR"))
            if error_count > 0:
                print(f"\n{error_count} error(s) found — fix before packaging.")
            else:
                print("\nNo errors found (warnings only).")
        else:
            print("No issues found — plugin directory looks good.")
        return

    pack_plugin(
        plugin_dir=args.plugin_dir,
        output_dir=args.output,
        version=version,
    )


if __name__ == "__main__":
    main()
